#!/command/with-contenv sh

if [ "$LSYNCD" = "true" ]; then
    echo "+正在启动Lsyncd守护进程，请编辑/conf/lsyncd/lsyncd.conf配置文件..."
	lsyncd -log Exec /conf/lsyncd/lsyncd.conf
else
    s6-svc -Od .
    exit 0
fi