#!/command/with-contenv sh

if [ "$CRON" = "true" ]; then
    echo "+正在启动系统crontabs服务，请编辑/conf/cron/crontabs文件..."
    /usr/sbin/crond -b -L /dev/null
    # 检测文件变化并执行命令
    md5_old=$(md5sum /conf/cron/crontabs | cut -d ' ' -f1)
    while :
    do
        md5_new=$(md5sum /conf/cron/crontabs | cut -d ' ' -f1)
        if [ "$md5_old" != "$md5_new" ]; then
            md5_old=$md5_new
            echo "$(date "+%Y-%m-%d %H:%M:%S") 检测到计划任务规则发生变化，重启crond服务"
            pid_old=$(pgrep -f "/usr/sbin/crond")
            if [ -n "$pid_old" ]; then
                kill -15 "$pid_old" || kill -9 "$pid_old"
                echo "stopping... pid：$pid_old"
            fi
            /usr/sbin/crond -b -L /dev/null
            pid_new=$(pgrep -f "/usr/sbin/crond")
            echo "running... pid：$pid_new"
        fi
        sleep 60
    done

else
    s6-svc -Od .
    exit 0
fi